### ISSUE TITLE
menu options dont do anything

### ISSUE THREAD

**Issue by zxq5-dev** [fr33zing/fr33zmenu#1]
so ive installed the menu and configured it, all of the entries show up correctly, but when i press enter on any of the options, the menu exits and nothing happens, im assuming that the program is crashing but im not sure why, ill send a ss of a log if i can find one

**Comment by zxq5-dev** [comment]
writing the output of the program to a log file simply outputs the name of the command that was supposedly executed

**Comment by fr33zing** [comment]
Without using the `--exec` or `--exec-with` options, it will only print the selection to stdout by default. This behavior is meant to mirror the default behavior of similar programs (dmenu for example) so that it can be used in shell scripts. If you're using one of those options and still having this issue, that's definitely a bug. In that case, please post your config file and the command or script you're using to run the program. Otherwise, it's a deficiency in my documentation and the usage section of the README needs a note about this. Either way, thanks for bringing this to my attention.

See `fn submit` in main.rs, specifically [line 154](https://github.com/fr33zing/fr33zmenu/blob/main/src/main.rs#L154) for the relevant bit of code

**Comment by zxq5-dev** [comment]
ohh i didnt realise you had to add the exec option to the end XD, thanks

**Comment by zxq5-dev** [comment]
i tried running it with the --exec option but that made no difference

**Comment by zxq5-dev** [comment]
![image](https://user-images.githubusercontent.com/80643031/224581152-cdea90d1-d409-45cb-aa60-aa73bcf4fac2.png)

this is the command i ran and the config i'm using

i know a bit of rust so i might have a go at trying to find the issue

**Comment by zxq5-dev** [comment]
ok i was just being an idiot, i was trying to run command line apps using the launcher which clearly the 'nohup' command in the execute function doesnt like, it worked with firefox after removing the args i gave it in my config.

is there an argument i can add to the config to allow cli apps to run? (because none of my cli apps work otherwise)

EDIT: opened a pull request that allows command line apps to work properly in the original shell the menu was run in
